In [1]:
import pandas as pd

df = pd.read_csv("IMDB Dataset.csv", engine="python", on_bad_lines="skip")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [2]:
df["sentiment"].value_counts()

sentiment
negative    2783
positive    2721
Name: count, dtype: int64

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
vectorizer = TfidfVectorizer(max_features=5000)

X = vectorizer.fit_transform(df["review"])
y = df["sentiment"]

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [6]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [7]:
model.score(X_test, y_test)

0.8664850136239782

In [8]:
model.predict(vectorizer.transform(["This movie was amazing"]))

array(['positive'], dtype=object)

In [9]:
model.predict(vectorizer.transform(["Worst movie ever"]))

array(['negative'], dtype=object)

### Day 52 Insight

Using TF-IDF improved text representation compared to CountVectorizer.
Better features led to improved model performance.